/// Autogenerated file

// swiftlint:disable all
import UIKit

/// Entry point for the app stylesheet
public class SkypeStyle: TeamsStyle {

	//MARK: - SkypeStyleColor
	override public func ColorStyle() -> TeamsStyle.ColorAppearanceProxy {
		if let override = _Color { return override }
			return SkypeStyleColorAppearanceProxy()
		}
	public class SkypeStyleColorAppearanceProxy: TeamsStyle.ColorAppearanceProxy {

		//MARK: - SkypeStyleColorred
		override public func redStyle() -> TeamsStyle.ColorAppearanceProxy.redAppearanceProxy {
			if let override = _red { return override }
				return SkypeStyleColorredAppearanceProxy()
			}
		public class SkypeStyleColorredAppearanceProxy: TeamsStyle.ColorAppearanceProxy.redAppearanceProxy {

			//MARK: r01 
			override public func r01Property(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> UIColor {
				if let override = _r01 { return override }
					return UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
				}
		}


		//MARK: yellow 
		fileprivate var _yellow: UIColor?
		public func yellowProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> UIColor {
			if let override = _yellow { return override }
			return UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
			}
		public var yellow: UIColor {
			get { return self.yellowProperty() }
			set { _yellow = newValue }
		}
	}

}