/// Autogenerated file

// swiftlint:disable all
import UIKit

/// Entry point for the app stylesheet
public class StyleDark: StyleGeneric {

	//MARK: - StyleDarkColor
	override public func ColorStyle() -> StyleGeneric.ColorAppearanceProxy {
		if let override = _Color { return override }
			return StyleDarkColorAppearanceProxy()
		}
	public class StyleDarkColorAppearanceProxy: StyleGeneric.ColorAppearanceProxy {

		//MARK: - StyleDarkColorred
		override public func redStyle() -> StyleGeneric.ColorAppearanceProxy.redAppearanceProxy {
			if let override = _red { return override }
				return StyleDarkColorredAppearanceProxy()
			}
		public class StyleDarkColorredAppearanceProxy: StyleGeneric.ColorAppearanceProxy.redAppearanceProxy {

			//MARK: r01 
			override public func r01Property(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> UIColor {
				if let override = _r01 { return override }
					return UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
				}
		}


		//MARK: yellow 
		fileprivate var _yellow: UIColor?
		public func yellowProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> UIColor {
			if let override = _yellow { return override }
			return UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
			}
		public var yellow: UIColor {
			get { return self.yellowProperty() }
			set { _yellow = newValue }
		}
	}

}