/// Autogenerated file

// swiftlint:disable all
import UIKit

public enum Theme: Int {
	case teams
	case skype

	public var stylesheet: TeamsStyle {
		switch self {
		case .teams: return TeamsStyle.shared()
		case .skype: return SkypeStyle.shared()
		}
	}
}

public class StylesheetManager {
	@objc dynamic public class func stylesheet(_ stylesheet: TeamsStyle) -> TeamsStyle {
		return StylesheetManager.default.theme.stylesheet
	}

	private struct DefaultKeys {
		static let theme = "theme"
	}

	public static let `default` = StylesheetManager()

	public var theme: Theme {
		didSet { UserDefaults.standard[DefaultKeys.theme] = theme }
	}

	public init() {
		self.theme = UserDefaults.standard[DefaultKeys.theme] ?? .teams
	}
}

public class Application {
	@objc dynamic public class func preferredContentSizeCategory() -> UIContentSizeCategory {
		return .large
	}
}

fileprivate var __ApperanceProxyHandle: UInt8 = 0

/// Your view should conform to 'AppearaceProxyComponent'.
public protocol AppearaceProxyComponent: class {
	associatedtype ApperanceProxyType
	var appearanceProxy: ApperanceProxyType { get }
	func didChangeAppearanceProxy()
}

/// Entry point for the app stylesheet
public class TeamsStyle: NSObject {

	class func shared() -> TeamsStyle {
		 struct __ { static let _sharedInstance = TeamsStyle() }
		return __._sharedInstance
	}
	//MARK: - Button
	public var _Button: ButtonAppearanceProxy?
	open func ButtonStyle() -> ButtonAppearanceProxy {
		if let override = _Button { return override }
			return ButtonAppearanceProxy()
		}
	public var Button: ButtonAppearanceProxy {
		get { return self.ButtonStyle() }
		set { _Button = newValue }
	}
	public class ButtonAppearanceProxy {

		//MARK: - color
		public var _color: colorAppearanceProxy?
		open func colorStyle() -> colorAppearanceProxy {
			if let override = _color { return override }
				return colorAppearanceProxy()
			}
		public var color: colorAppearanceProxy {
			get { return self.colorStyle() }
			set { _color = newValue }
		}
		public class colorAppearanceProxy {

			//MARK: c1 
			public var _c1: UIColor?
			open func c1Property(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> UIColor {
				if let override = _c1 { return override }
					return StylesheetManager.stylesheet(TeamsStyle.shared()).Color.black.b1Property(traitCollection)
				}
			public var c1: UIColor {
				get { return self.c1Property() }
				set { _c1 = newValue }
			}
		}

	}
	//MARK: - Color
	public var _Color: ColorAppearanceProxy?
	open func ColorStyle() -> ColorAppearanceProxy {
		if let override = _Color { return override }
			return ColorAppearanceProxy()
		}
	public var Color: ColorAppearanceProxy {
		get { return self.ColorStyle() }
		set { _Color = newValue }
	}
	public class ColorAppearanceProxy {

		//MARK: - black
		public var _black: blackAppearanceProxy?
		open func blackStyle() -> blackAppearanceProxy {
			if let override = _black { return override }
				return blackAppearanceProxy()
			}
		public var black: blackAppearanceProxy {
			get { return self.blackStyle() }
			set { _black = newValue }
		}
		public class blackAppearanceProxy {

			//MARK: b1 
			public var _b1: UIColor?
			open func b1Property(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> UIColor {
				if let override = _b1 { return override }
					return UIColor(red: 0.14509805, green: 0.14117648, blue: 0.13725491, alpha: 1.0)
				}
			public var b1: UIColor {
				get { return self.b1Property() }
				set { _b1 = newValue }
			}
		}

	}

}
extension Button: AppearaceProxyComponent {

	public typealias ApperanceProxyType = TeamsStyle.ButtonAppearanceProxy
	public var appearanceProxy: ApperanceProxyType {
		get {
			guard let proxy = objc_getAssociatedObject(self, &__ApperanceProxyHandle) as? ApperanceProxyType else { return StylesheetManager.stylesheet(TeamsStyle.shared()).Button }
			return proxy
		}
		set {
			objc_setAssociatedObject(self, &__ApperanceProxyHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			didChangeAppearanceProxy()
		}
	}
}
