/// Autogenerated file

// swiftlint:disable all
import UIKit

fileprivate extension UserDefaults {
	subscript<T>(key: String) -> T? {
		get { return value(forKey: key) as? T }
		set { set(newValue, forKey: key) }
	}

	subscript<T: RawRepresentable>(key: String) -> T? {
		get {
			if let rawValue = value(forKey: key) as? T.RawValue {
				return T(rawValue: rawValue)
			}
			return nil
		}
		set { self[key] = newValue?.rawValue }
	}
}

public enum Theme: Int {
	case skype
	case teams

	public var stylesheet: TeamsStyle {
		switch self {
		case .skype: return SkypeStyle.shared()
		case .teams: return TeamsStyle.shared()
		}
	}
}

public extension Notification.Name {
	static let didChangeTheme = Notification.Name("stylesheet.theme")
}

public class StylesheetManager {
	@objc dynamic public class func stylesheet(_ stylesheet: TeamsStyle) -> TeamsStyle {
		return StylesheetManager.default.theme.stylesheet
	}

	private struct DefaultKeys {
		static let theme = "theme"
	}

	public static let `default` = StylesheetManager()
	public static var S: TeamsStyle {
		return StylesheetManager.default.theme.stylesheet
	}

	public var theme: Theme {
		didSet {
			NotificationCenter.default.post(name: .didChangeTheme, object: theme)
			UserDefaults.standard[DefaultKeys.theme] = theme
		}
	}

	public init() {
		self.theme = UserDefaults.standard[DefaultKeys.theme] ?? .teams
	}
}

public class Application {
	@objc dynamic public class func preferredContentSizeCategory() -> UIContentSizeCategory {
		return .large
	}
}

fileprivate var __ApperanceProxyHandle: UInt8 = 0
fileprivate var __ThemeAwareHandle: UInt8 = 0
fileprivate var __ObservingDidChangeThemeHandle: UInt8 = 0

/// Your view should conform to 'AppearaceProxyComponent'.
public protocol AppearaceProxyComponent: class {
	associatedtype ApperanceProxyType
	var appearanceProxy: ApperanceProxyType { get }
	var themeAware: Bool { get set }
	func didChangeAppearanceProxy()
}

public extension AppearaceProxyComponent {
	public func initAppearanceProxy(themeAware: Bool = true) {
		self.themeAware = themeAware
		didChangeAppearanceProxy()
	}
}

fileprivate var __AnimatorProxyHandle: UInt8 = 0

/// Your view should conform to 'AnimatorProxyComponent'.
public protocol AnimatorProxyComponent: class {
	associatedtype AnimatorProxyType
	var animator: AnimatorProxyType { get }

}

/// Entry point for the app stylesheet
public class TeamsStyle: NSObject {

	public class func shared() -> TeamsStyle {
		 struct __ { static let _sharedInstance = TeamsStyle() }
		return __._sharedInstance
	}
	//MARK: - Metric
	public var _Metric: MetricAppearanceProxy?
	open func MetricStyle() -> MetricAppearanceProxy {
		if let override = _Metric { return override }
			return MetricAppearanceProxy()
		}
	public var Metric: MetricAppearanceProxy {
		get { return self.MetricStyle() }
		set { _Metric = newValue }
	}
	public class MetricAppearanceProxy {

		//MARK: test 
		public var _test: CGFloat?
		open func testProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> CGFloat {
			if let override = _test { return override }
			return CGFloat(10.0)
			}
		public var test: CGFloat {
			get { return self.testProperty() }
			set { _test = newValue }
		}
	}
	//MARK: - TimingFunctions
	public var _TimingFunctions: TimingFunctionsAppearanceProxy?
	open func TimingFunctionsStyle() -> TimingFunctionsAppearanceProxy {
		if let override = _TimingFunctions { return override }
			return TimingFunctionsAppearanceProxy()
		}
	public var TimingFunctions: TimingFunctionsAppearanceProxy {
		get { return self.TimingFunctionsStyle() }
		set { _TimingFunctions = newValue }
	}
	public class TimingFunctionsAppearanceProxy {

		//MARK: easeIn 
		public var _easeIn: CAMediaTimingFunction?
		open func easeInProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> CAMediaTimingFunction {
			if let override = _easeIn { return override }
			return CAMediaTimingFunction(controlPoints: 1.0, 0.0, 0.78, 1.0)
			}
		public var easeIn: CAMediaTimingFunction {
			get { return self.easeInProperty() }
			set { _easeIn = newValue }
		}
	}
	//MARK: - Color
	public var _Color: ColorAppearanceProxy?
	open func ColorStyle() -> ColorAppearanceProxy {
		if let override = _Color { return override }
			return ColorAppearanceProxy()
		}
	public var Color: ColorAppearanceProxy {
		get { return self.ColorStyle() }
		set { _Color = newValue }
	}
	public class ColorAppearanceProxy {

		//MARK: yellow 
		public var _yellow: UIColor?
		open func yellowProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> UIColor {
			if let override = _yellow { return override }
			return UIColor(red: 0.0, green: 0.47058824, blue: 0.83137256, alpha: 1.0)
			}
		public var yellow: UIColor {
			get { return self.yellowProperty() }
			set { _yellow = newValue }
		}
	}
	//MARK: - Animator
	public var _Animator: AnimatorAnimatorProxy?
	open func AnimatorAnimator() -> AnimatorAnimatorProxy {
		if let override = _Animator { return override }
			return AnimatorAnimatorProxy()
		}
	public var Animator: AnimatorAnimatorProxy {
		get { return self.AnimatorAnimator() }
		set { _Animator = newValue }
	}
	open class AnimatorAnimatorProxy {
		public struct KeyFrame {
			var time: Float?
			var timing: CAMediaTimingFunction?
		}

		public init() {}

		//MARK: - basic
		public var _basic: basicAppearanceProxy?
		open func basicStyle() -> basicAppearanceProxy {
			if let override = _basic { return override }
				return basicAppearanceProxy()
			}
		public var basic: basicAppearanceProxy {
			get { return self.basicStyle() }
			set { _basic = newValue }
		}
		public class basicAppearanceProxy {

		//MARK: duration 
		public var _duration: CGFloat?
		open func durationProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> CGFloat {
			if let override = _duration { return override }
			return CGFloat(2.0)
			}
		public var duration: CGFloat {
			get { return self.durationProperty() }
			set { _duration = newValue }
		}

		//MARK: keyFrames 
		public var _keyFrames: [KeyFrame]?
		open func keyFramesProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> [KeyFrame] {
			if let override = _keyFrames { return override }
			return [
			KeyFrame(time: 0.0, timing: nil), 
			KeyFrame(time: 0.4, timing: 
			TimingFunctions.easeInProperty(traitCollection))]
			}
		public var keyFrames: [KeyFrame] {
			get { return self.keyFramesProperty() }
			set { _keyFrames = newValue }
		}
		}
	

}
}
extension UIView: AnimatorProxyComponent {

	public typealias AnimatorProxyType = TeamsStyle.AnimatorAnimatorProxy
	public var animator: AnimatorProxyType {
		get {
			guard let a = objc_getAssociatedObject(self, &__AnimatorProxyHandle) as? AnimatorProxyType else { return StylesheetManager.stylesheet(TeamsStyle.shared()).Animator }
			return a
		}
		set {
			objc_setAssociatedObject(self, &__AnimatorProxyHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
		}
	}
}
